<?php

declare(strict_types=1);

namespace Tests\Macbim\SyliusGiftCardsPlugin\Model;

use Doctrine\ORM\Mapping as ORM;
use Macbim\SyliusGiftCardsPlugin\Model\OrderInterface;
use Macbim\SyliusGiftCardsPlugin\Model\OrderTrait as MacBimGiftCardsPluginOrderTrait;
use Sylius\Component\Core\Model\Order as BaseOrder;
use Sylius\Component\Promotion\Model\PromotionCouponInterface as BaseCouponInterface;

#[ORM\Entity]
#[ORM\Table(name: 'sylius_order')]
class Order extends BaseOrder implements OrderInterface
{
    use MacBimGiftCardsPluginOrderTrait {
        __construct as private initializeOrderTrait;
    }

    public function __construct()
    {
        parent::__construct();

        $this->initializeOrderTrait();
    }

    public function setPromotionCoupon(?BaseCouponInterface $coupon): void
    {
        parent::setPromotionCoupon($coupon); // TODO: Change the autogenerated stub
    }
}
